### ISSUE TITLE
Any command to create IoStore format (pak + utoc + ucas) with UnrealPak

### ISSUE THREAD

**Issue by josuigoa** [Dmgvol/UE_Modding#3]
Hi!

first of all, thanks for all the tutorials!

I've got a game with IoStore fiels (mini pak file, utoc and ucas). I could extract the assets with the UnrealPak following your tutorial. But when I go to pack it back, I'm not able to create the three files of IoStore, I only get a bigger pak than before.

Do you know if there any command to create those three files with UnrealPak?

**Comment by Dmgvol** [comment]
UnrealPak doesn't support IoStore, mostly UE4 games or mod files that are not part of the IoStore of the Pak file like config files.

In order to modify IoStore assets you need to use [ZenTools ](https://github.com/Archengius/ZenTools ) to properly extract both uasset and uexp files.
The packaging part is a bit tricky. and is not done using unrealPak but with UnrealEngine...
